INSERT INTO public.committees (id, slug, name, short_name, category, tagline, established, instagram_url) VALUES
('acm','acm','DJS ACM','ACM','Student Chapters','Computing machinery, made human.',2004,'https://www.instagram.com/djsanghvi_acm/'),
('sigai','sigai','DJS ACM SIGAI','SIGAI','Student Chapters','Special interest. Generally intelligent.',2021,'https://www.instagram.com/djs_sigai/'),
('djscsi','djscsi','DJS CSI','CSI','Student Chapters','Codebases, careers, and community.',2007,'https://www.instagram.com/djs.csi/'),
('iete','iete','DJS IETE','IETE','Student Chapters','Telecommunications and beyond.',2001,'https://www.instagram.com/djsce_iete/'),
('isme','isme','DJS ISME','ISME','Student Chapters','Mechanical minds, moving parts.',2010,'https://www.instagram.com/djsce_isme/'),
('sae','sae','DJS SAE','SAE','Student Chapters','Vehicles, velocity, victory.',1992,'https://www.instagram.com/djsce_sae/'),
('s4ds','s4ds','DJS S4DS','S4DS','Student Chapters','Distributions, decisions, dashboards.',2019,'https://www.instagram.com/djs_s4ds/'),
('isaca','isaca','DJS ISACA','ISACA','Student Chapters','Audit, govern, secure.',2015,'https://www.instagram.com/isacadjsce/'),
('nsdc','nsdc','DJS NSDC','NSDC','Student Chapters','Skills for tomorrow''s economy.',2016,'https://www.instagram.com/djs.nsdc/'),
('gdg','gdg','DJS GDSC','GDSC','Student Chapters','Build with Google. Build for the world.',2019,'https://www.instagram.com/gdg_djsce/'),
('ieee','ieee','DJS IEEE','IEEE','Student Chapters','Engineers, signals, and the noise between.',1998,'https://www.instagram.com/djs_ieee/'),
('unicode','unicode','DJS Unicode','Unicode','Tech Committees','Web, app, and product engineering.',2016,'https://www.instagram.com/unicode.djsce/'),
('synapse','synapse','DJS Synapse','Synapse','Tech Committees','Neural pathways across departments.',2018,'https://www.instagram.com/synapse.djsce/'),
('init','init','DJS Init.ai','Init.ai','Tech Committees','First-year on-ramp to engineering.',2017,'https://www.instagram.com/djs_init.ai/'),
('codeai','codeai','DJS CodeAI','CodeAI','Tech Committees','Models, math, and machine intuition.',2020,'https://www.instagram.com/djscodeai/'),
('compute','compute','DJS Compute','Compute','Tech Committees','Systems, networks, infrastructure.',2013,'https://www.instagram.com/djscompute/'),
('microminds','microminds','DJS Microminds','Microminds','Tech Committees','Embedded, by intent.',2012,'https://www.instagram.com/djs.microminds/'),
('infomatrix','infomatrix','DJS Infomatrix','Infomatrix','Tech Committees','The annual technical festival.',1995,'https://www.instagram.com/djsinfomatrix/'),
('iic','iic','DJS IIC','IIC','Clubs','From idea to incubation.',2018,'https://www.instagram.com/iic_djsce/'),
('trinity','trinity','DJS Trinity','Trinity','Clubs','Theatre, dramatised.',2007,'https://www.instagram.com/djsce.trinity/'),
('nss','nss','DJS NSS','NSS','Clubs','Service before self.',1985,'https://www.instagram.com/nss_djsanghvi/'),
('codestars','codestars','DJS Codestars','Codestars','Clubs','Where competitive coders are forged.',2014,'https://www.instagram.com/djsce_codestars/'),
('litsoc','litsoc','DJS LITSOC','LITSOC','Clubs','Words, weighted.',1996,'https://www.instagram.com/djsce_litsoc/'),
('beats','beats','DJS Beats','Beats','Clubs','The music collective.',2003,'https://www.instagram.com/beats.djs/'),
('aura','aura','DJS Aura','Aura','Clubs','Fashion as language.',2009,'https://www.instagram.com/aura.djsce/'),
('panache','panache','DJS Panache','Panache','Clubs','The runway showcase.',2010,'https://www.instagram.com/panache.djsce/'),
('dhadak','dhadak','DJS Dhadak','Dhadak','Clubs','Dance, in heartbeats.',2005,'https://www.instagram.com/dhadak.djsce/'),
('express','express','DJS Express','Express','Clubs','The publication of record.',1998,'https://www.instagram.com/djsce.express/'),
('munsoc','munsoc','DJS MUNSOC','MUNSOC','Clubs','Diplomacy, debated.',2001,'https://www.instagram.com/djsce_munsoc/'),
('ecell','ecell','DJS E-Cell','E-Cell','Clubs','Founders, in the making.',2012,'https://www.instagram.com/ecell_djsce/'),
('nova','nova','DJS NOVA','NOVA','Clubs','Innovation, sparked.',2014,'https://www.instagram.com/djs.nova/'),
('consulting','consulting','DJS Consulting Group (DCG)','DCG','Clubs','Strategy, simulated.',2017,'https://www.instagram.com/djsconsultinggroup/'),
('tedx','tedx','DJS TEDx','TEDx','Clubs','Ideas worth amplifying.',2015,'https://www.instagram.com/tedxdjsce/'),
('racing','racing','DJS Racing','Racing','SAE Teams','Formula collegiate.',2007,'https://www.instagram.com/djsracingindia/'),
('karting','karting','DJS Karting','Karting','SAE Teams','Carbon-fiber. Apex hunter.',2009,'https://www.instagram.com/djskartingindia/'),
('skylark','skylark','DJS Skylark','Skylark','SAE Teams','Adventure & trekking.',2013,'https://www.instagram.com/djsskylark/'),
('helios','helios','DJS Helios','Helios','SAE Teams','Solar-powered, future-bound.',2016,'https://www.instagram.com/djs_helios/'),
('phoenix','phoenix','DJS Phoenix','Phoenix','SAE Teams','Athletics committee.',2008,'https://www.instagram.com/djscephoenix/'),
('speedsters','speedsters','DJS Speedster','Speedster','SAE Teams','Supra. Sustained.',2011,'https://www.instagram.com/djs_speedsters/'),
('miles','miles','DJS Miles','Miles','SAE Teams','Service, in motion.',2002,'https://www.instagram.com/djs_miles/'),
('astra','astra','DJS Astra','Astra','SAE Teams','All-terrain ambitions.',2014,'https://www.instagram.com/djs.astra/'),
('kronos','kronos','DJS Kronos','Kronos','SAE Teams','Endurance, engineered.',2015,'https://www.instagram.com/djs_kronos_india/'),
('impulse','impulse','DJS Impulse','Impulse','SAE Teams','Sports, sharpened.',2006,'https://www.instagram.com/djs_impulse/'),
('robocon','robocon','DJS Robocon','Robocon','SAE Teams','Autonomous machines, championship rules.',2008,'https://www.instagram.com/djsrobocon/'),
('djsantariksh','djsantariksh','DJS Antariksh','Antariksh','IETE Teams','Astronomy, made earthly.',2011,'https://www.instagram.com/djsantariksh/'),
('arya','arya','DJS Arya','Arya','IETE Teams','The cultural heartbeat.',1989,'https://www.instagram.com/djs_arya/')
ON CONFLICT (id) DO NOTHING;
